//
//  NewsfeedInteractor.swift
//  KalchabekNurbekov_vk
//
//  Created by Kalchabek Nurbekov on 11.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsfeedBusinessLogic {
    func doSomething(request: Newsfeed.Something.Request.RequestType)
}


class NewsfeedInteractor: NewsfeedBusinessLogic {
    
    
    var presenter: NewsfeedPresentationLogic?
    var service: NewsfeedService?
    //var name: String = ""
    private var fetcher: DataFetcher = NetworkDataFetcher(networking: NetworkService())
    
    // MARK: Do something
    
    func doSomething(request: Newsfeed.Something.Request.RequestType) {

        if service == nil {
            service = NewsfeedService()
        }
        switch request {
            
            
        case .getNewsfeed:
            fetcher.getFeed { [weak self] (feedResponse) in
                
                guard let feedResponse = feedResponse else { return }
                self?.presenter?.presentSomething(response: .presentNewsfeed(feed: feedResponse))
            }
        }
        
    }
}
